export const Physics = [
  { name: 'Kinematics', idNo: 0 },
  { name: 'Newton’s laws of motion', idNo: 1 },
  { name: 'Work Power Energy', idNo: 2 },
  { name: 'Systems of particles and Rotational Motion', idNo: 3 },
  { name: 'Gravitation', idNo: 4 },
  { name: 'Mechanical Properties of Solids', idNo: 5 },
  { name: 'Mechanical Properties of Fluids', idNo: 6 },
  { name: 'Thermal Properties of Matter', idNo: 7 },
  { name: 'Thermodynamics', idNo: 8 },
  { name: 'Kinetic Theory', idNo: 9 },
  { name: 'Oscillations', idNo: 10 },
  { name: 'Waves', idNo: 11 },
  { name: 'ELECTRIC CHARGES AND FIELDS ', idNo: 12 },
  { name: 'ELECTROSTATIC POTENTIAL AND CAPACITANCE', idNo: 13 },
  { name: 'CURRENT ELECTRICITY', idNo: 14 },
  { name: 'MOVING CHARGES AND MAGNETISM', idNo: 15 },
  { name: 'MAGNETISM AND MATTER', idNo: 16 },
  { name: 'ELECTROMAGNETIC INDUCTION', idNo: 17 },
  { name: 'ALTERNATING CURRENT ', idNo: 18 },
  { name: 'ELECTROMAGNETIC WAVES', idNo: 19 },
  { name: 'RAY OPTICS AND OPTICAL INSTRUMENTS', idNo: 20 },
  { name: 'WAVE OPTICS', idNo: 21 },
  { name: 'DUAL NATURE OF RADIATION AND MATTER', idNo: 22 },
  { name: 'SEMICONDUCTOR ', idNo: 23 },
  { name: 'MODERN PHYSICS', idNo: 24 },
];
export const Chemistry = [
  { name: 'Some Basic,Mole Concept,Balance Equations', idNo: 0 },
  { name: 'Gaseous and Liquids States', idNo: 1 },
  { name: 'Atomic Structure', idNo: 2 },
  { name: 'Chemical Bonding and Molecular Structure', idNo: 3 },
  { name: 'Energetics', idNo: 4 },
  { name: 'Equilibrium', idNo: 5 },
  { name: 'ElectroChemistry', idNo: 6 },
  { name: 'Chamical Kinetics', idNo: 7 },
  { name: 'Solid State', idNo: 8 },
  { name: 'Solutions', idNo: 9 },
  { name: 'Nuclear Chemistry', idNo: 10 },
  { name: 'S and P block Elements', idNo: 11 },
  { name: 'D and F block Elements', idNo: 12 },
  { name: 'Metallurgy', idNo: 13 },
  { name: 'Principles of Qualitative Analysis', idNo: 14 },
  { name: 'General Organic Chemistry', idNo: 15 },
  { name: 'Hydrocarbons', idNo: 16 },
  { name: 'Organic Compunds Containing Halogens', idNo: 17 },
  { name: 'Alcohols Phenols Ethers', idNo: 18 },
  { name: 'Aldehyde and Ketones', idNo: 19 },
  { name: 'Carboxylic Acids and Derivatives', idNo: 20 },
  { name: 'Organic Compunds Containing Nitrogen', idNo: 21 },
  { name: 'Practical Organic Chemistry', idNo: 22 },
];
export const MatheMatics = [
  { name: 'Sets, Relation and Function', idNo: 0 },
  { name: 'Complex Number', idNo: 1 },
  { name: 'Quadratic Equations', idNo: 2 },
  { name: 'Probability', idNo: 3 },
  { name: 'Arithmetic and Geometric Progressions', idNo: 4 },
  { name: 'Logarithms', idNo: 5 },
  { name: 'Straight Line', idNo: 6 },
  { name: 'Circle', idNo: 7 },
  { name: 'Parabola', idNo: 8 },
  { name: 'Ellips', idNo: 9 },
  { name: 'Hyperbola', idNo: 10 },
  { name: 'Permutation and Combinations', idNo: 11 },
  { name: 'Binomial Theorem', idNo: 12 },
  { name: 'Trigonometry', idNo: 13 },
  { name: 'Probability', idNo: 14 },
  { name: 'Matrices and Determinant', idNo: 15 },
  { name: 'Limits, continuity and Differentiability', idNo: 16 },
  { name: 'Differentiations', idNo: 17 },
  { name: 'Applications of Differentiations', idNo: 18 },
  { name: 'Integrals ', idNo: 19 },
  { name: 'Application of Integrals', idNo: 20 },
  { name: 'Differential equations', idNo: 21 },
  { name: 'Vectors Algebra', idNo: 22 },
  { name: 'Three Dimensios Geometry', idNo: 23 },
];
